import Foundation

// Dizionario delle correzioni automatiche per ClearPad
// Questo file contiene un insieme di sostituzioni testuali
// utilizzate per correggere errori comuni di digitazione,
// accenti, doppie lettere e forme errate ricorrenti.
let correzioni: [String: String] = [
    "a fiancoo": "a fianco",
    "accaderee": "accadere",
    "accadutoo": "accaduto",
    "accadutooo": "accaduto",
    "accellerare": "accelerare",
    "accellerato": "accelerato",
    "accellerazione": "accelerazione",
    "accoglientee": "accogliente",
    "accoglienteee": "accogliente",
    "accompagnaree": "accompagnare",
    "accompagnareee": "accompagnare",
    "acquai": "acquai",
    "acquaioo": "acquaio",
    "acquistaree": "acquistare",
    "acquistareee": "acquistare",
    "adattaree": "adattare",
    "adattareee": "adattare",
    "addiritura": "addirittura",
    "addirritura": "addirittura",
    "addirttura": "addirittura",
    "affianco": "a fianco",
    "affiancoo": "a fianco",
    "affrontaree": "affrontare",
    "affrontareee": "affrontare",
    "afianco": "a fianco",
    "aggionamento": "aggiornamento",
    "aggiornameto": "aggiornamento",
    "aggiornamnto": "aggiornamento",
    "aggiornaree": "aggiornare",
    "aggiornareee": "aggiornare",
    "aggiornmento": "aggiornamento",
    "aggire": "agire",
    "aggisce": "agisce",
    "aggiscono": "agiscono",
    "aiutaree": "aiutare",
    "aiutareee": "aiutare",
    "all inizio": "all’inizio",
    "almeno che": "a meno che",
    "almneo": "almeno",
    "altretanto": "altrettanto",
    "altretantoo": "altrettanto",
    "altretnto": "altrettanto",
    "alzaree": "alzare",
    "alzareee": "alzare",
    "amaree": "amare",
    "amareee": "amare",
    "amche": "anche",
    "analizzaree": "analizzare",
    "analizzareee": "analizzare",
    "anchee": "anche",
    "ancheee": "anche",
    "ancoraa": "ancora",
    "andaree": "andare",
    "andareee": "andare",
    "andiamoo": "andiamo",
    "andiamooo": "andiamo",
    "annunciaree": "annunciare",
    "annunciareee": "annunciare",
    "antanni": "antani",
    "apena": "appena",
    "appariree": "apparire",
    "apparrire": "apparire",
    "apparte": "a parte",
    "appenaa": "appena",
    "appenaaa": "appena",
    "applicaree": "applicare",
    "applicareee": "applicare",
    "apriree": "aprire",
    "aprireee": "aprire",
    "arivare": "arrivare",
    "arrivaree": "arrivare",
    "arrivareee": "arrivare",
    "arrivatoo": "arrivato",
    "ascoltaree": "ascoltare",
    "ascoltareee": "ascoltare",
    "ascoltoo": "ascolto",
    "ascoltoò": "ascolto",
    "aspettareee": "aspettare",
    "assaii": "assai",
    "assaiii": "assai",
    "assiccurazione": "assicurazione",
    "assicuraree": "assicurare",
    "assicurareee": "assicurare",
    "assicurazzione": "assicurazione",
    "assicurazzioni": "assicurazioni",
    "attacare": "attaccare",
    "attacaree": "attaccare",
    "attacareee": "attaccare",
    "attenderee": "attendere",
    "attendereee": "attendere",
    "attimoe": "attimo",
    "attimoo": "attimo",
    "avanzaree": "avanzare",
    "avanzareee": "avanzare",
    "averee": "avere",
    "avereee": "avere",
    "avvicinaree": "avvicinare",
    "avvicinareee": "avvicinare",
    "avolte": "a volte",
    "avvolte": "a volte",
    "avvoltee": "a volte",
    "baciaree": "baciare",
    "baciareee": "baciare",
    "bagnio": "bagno",
    "bagnioo": "bagno",
    "ballaree": "ballare",
    "ballareee": "ballare",
    "bastaa": "basta",
    "bastaaa": "basta",
    "bastaree": "bastare",
    "bastareee": "bastare",
    "batteree": "battere",
    "battereee": "battere",
    "beene": "bene",
    "beenee": "bene",
    "belissimo": "bellissimo",
    "bellisimo": "bellissimo",
    "bellisssimo": "bellissimo",
    "beree": "bere",
    "bereee": "bere",
    "bisognaa": "bisogna",
    "bisognaaa": "bisogna",
    "bisognaree": "bisognare",
    "bisognareee": "bisognare",
    "bloccaree": "bloccare",
    "bloccareee": "bloccare",
    "bravoo": "bravo",
    "bravooo": "bravo",
    "brillaree": "brillare",
    "brillareee": "brillare",
    "caderee": "cadere",
    "cadereee": "cadere",
    "caffe'": "caffè",
    "caffèè": "caffè",
    "calcolaree": "calcolare",
    "calcolareee": "calcolare",
    "camminaree": "camminare",
    "camminareee": "camminare",
    "cantaree": "cantare",
    "cantareee": "cantare",
    "capiree": "capire",
    "capireee": "capire",
    "capitatoo": "capitato",
    "capitatooo": "capitato",
    "carattereè": "carattere",
    "caratteree": "carattere",
    "caricaree": "caricare",
    "caricareee": "caricare",
    "ce erano": "c’erano",
    "ce ne": "ce n’è",
    "ce stata": "c’è stata",
    "ce stato": "c’è stato",
    "ce un": "c’è un",
    "ce una": "c’è una",
    "cercaree": "cercare",
    "cercareee": "cercare",
    "certamete": "certamente",
    "certamnete": "certamente",
    "che e": "che è",
    "cheé": "che è",
    "cheè": "che è",
    "chiacchieraree": "chiacchierare",
    "chiacchierareee": "chiacchierare",
    "chiederee": "chiedere",
    "chiedereee": "chiedere",
    "chissa": "chissà",
    "chissa'": "chissà",
    "chiuderee": "chiudere",
    "chiudereee": "chiudere",
    "cioe": "cioè",
    "cioe'": "cioè",
    "cioche": "ciò che",
    "cittàà": "città",
    "citta'": "città",
    "ciòche": "ciò che",
    "collaboraree": "collaborare",
    "collaborareee": "collaborare",
    "collegaree": "collegare",
    "collegareee": "collegare",
    "cominciaree": "cominciare",
    "cominciareee": "cominciare",
    "completaree": "completare",
    "completareee": "completare",
    "comprenderee": "comprendere",
    "comprendereee": "comprendere",
    "concluderee": "concludere",
    "concludereee": "concludere",
    "confermaree": "confermare",
    "confermareee": "confermare",
    "conosceree": "conoscere",
    "conoscereee": "conoscere",
    "consideraree": "considerare",
    "considerareee": "considerare",
    "consigliio": "consiglio",
    "consigliioo": "consiglio",
    "contaree": "contare",
    "contareee": "contare",
    "continuaree": "continuare",
    "continuareee": "continuare",
    "controllaree": "controllare",
    "controllareee": "controllare",
    "correggeree": "correggere",
    "correggereee": "correggere",
    "correree": "correre",
    "correreee": "correre",
    "cosache": "cosa che",
    "cosi": "così",
    "cosi'": "così",
    "cossì": "così",
    "cosìì": "così",
    "crearee": "creare",
    "creareee": "creare",
    "crederee": "credere",
    "credereee": "credere",
    "cresceree": "crescere",
    "crescereee": "crescere",
    "cucinaa": "cucina",
    "cucinaree": "cucinare",
    "cucinareee": "cucinare",
    "curaree": "curare",
    "curareee": "curare",
    "d accordo": "d’accordo",
    "daccord": "d’accordo",
    "daccordo": "d’accordo",
    "daltro": "d’altro",
    "davero": "davvero",
    "daverro": "davvero",
    "davveroò": "davvero",
    "dà": "da",
    "decideree": "decidere",
    "decidereee": "decidere",
    "descriveree": "descrivere",
    "descrivereee": "descrivere",
    "difficileee": "difficile",
    "difficille": "difficile",
    "difficillee": "difficile",
    "dimenticaree": "dimenticare",
    "dimenticareee": "dimenticare",
    "direiì": "direi",
    "direì": "direi",
    "dispiacee": "dispiace",
    "dispiaceee": "dispiace",
    "diventaree": "diventare",
    "diventareee": "diventare",
    "domanii": "domani",
    "domaniii": "domani",
    "domanì": "domani",
    "dovreei": "dovrei",
    "dovreii": "dovrei",
    "dovreiii": "dovrei",
    "eccoo": "ecco",
    "eccooo": "ecco",
    "effetivamente": "effettivamente",
    "effettivamete": "effettivamente",
    "effettivamnete": "effettivamente",
    "entratee": "entrate",
    "entrateee": "entrate",
    "esempioo": "esempio",
    "esempiooo": "esempio",
    "esperienzaa": "esperienza",
    "esperiennza": "esperienza",
    "esperienzza": "esperienza",
    "facileee": "facile",
    "facille": "facile",
    "facillee": "facile",
    "famigliaa": "famiglia",
    "famigliaaa": "famiglia",
    "faree": "fare",
    "fareee": "fare",
    "fattoo": "fatto",
    "fattooo": "fatto",
    "fà": "fa",
    "felicee": "felice",
    "feliceee": "felice",
    "finalmene": "finalmente",
    "finalmete": "finalmente",
    "finalmnte": "finalmente",
    "finalmnete": "finalmente",
    "finalmte": "finalmente",
    "finlamente": "finalmente",
    "finnalmente": "finalmente",
    "finoa": "fino a",
    "finoad": "fino ad",
    "forsee": "forse",
    "forseee": "forse",
    "fortunatamete": "fortunatamente",
    "fortunatamnete": "fortunatamente",
    "fortunatamte": "fortunatamente",
    "fotografiaa": "fotografia",
    "fotografiaaa": "fotografia",
    "fratelloo": "fratello",
    "fratellooo": "fratello",
    "frequenteemente": "frequentemente",
    "frequentemete": "frequentemente",
    "funzionaa": "funziona",
    "funzionaaa": "funziona",
    "funzine": "funzione",
    "generalee": "generale",
    "generaleee": "generale",
    "gentilee": "gentile",
    "gentileee": "gentile",
    "gia": "già",
    "gia'": "già",
    "giocaree": "giocare",
    "giocareee": "giocare",
    "giornoo": "giorno",
    "giornooo": "giorno",
    "giovedi": "giovedì",
    "giustoo": "giusto",
    "giustooo": "giusto",
    "guardaree": "guardare",
    "guardareee": "guardare",
    "ieriì": "ieri",
    "immediatamentee": "immediatamente",
    "immediatamete": "immediatamente",
    "immediatamnete": "immediatamente",
    "impararee": "imparare",
    "imparareee": "imparare",
    "imparrare": "imparare",
    "importantee": "importante",
    "importanteee": "importante",
    "impossibilee": "impossibile",
    "impossibileee": "impossibile",
    "incertezzaa": "incertezza",
    "incertezzaaa": "incertezza",
    "incontraree": "incontrare",
    "incontrareee": "incontrare",
    "indicaree": "indicare",
    "indicareee": "indicare",
    "infatti": "in fatti",
    "informazionee": "informazione",
    "informazioneee": "informazione",
    "iniziaree": "iniziare",
    "iniziareee": "iniziare",
    "inoltree": "inoltre",
    "inoltreee": "inoltre",
    "inquanto": "in quanto",
    "insiemee": "insieme",
    "insiemeee": "insieme",
    "insommaa": "insomma",
    "insommaaa": "insomma",
    "intantoo": "intanto",
    "intantooo": "intanto",
    "interessantee": "interessante",
    "interessanteee": "interessante",
    "interogazione": "interrogazione",
    "interooggazione": "interrogazione",
    "interrogazzione": "interrogazione",
    "invecee": "invece",
    "inveceee": "invece",
    "l hai": "l’hai",
    "l hanno": "l’hanno",
    "l ho": "l’ho",
    "lavoraree": "lavorare",
    "lavorareee": "lavorare",
    "leggeree": "leggere",
    "leggereee": "leggere",
    "lentamete": "lentamente",
    "lentamnete": "lentamente",
    "letteraa": "lettera",
    "letteraaa": "lettera",
    "libroo": "libro",
    "librooo": "libro",
    "limitatamete": "limitatamente",
    "limitatamnete": "limitatamente",
    "linguaa": "lingua",
    "linguaaa": "lingua",
    "lontanoo": "lontano",
    "lontanooo": "lontano",
    "lunedi": "lunedì",
    "magnificoo": "magnifico",
    "magnificooo": "magnifico",
    "manteneree": "mantenere",
    "mantenereee": "mantenere",
    "martedi": "martedì",
    "mattinaa": "mattina",
    "mattinaaa": "mattina",
    "mercoledi": "mercoledì",
    "miglioree": "migliore",
    "miglioreee": "migliore",
    "milionee": "milione",
    "milioneee": "milione",
    "minutoo": "minuto",
    "minutooo": "minuto",
    "moltissimoo": "moltissimo",
    "momentoo": "momento",
    "momentooo": "momento",
    "mondoo": "mondo",
    "mondooo": "mondo",
    "montagnaa": "montagna",
    "montagnaaa": "montagna",
    "mà": "ma",
    "neccessario": "necessario",
    "necesario": "necessario",
    "necessariamete": "necessariamente",
    "necessariamnete": "necessariamente",
    "nell altra": "nell’altra",
    "nell altro": "nell’altro",
    "nessunoo": "nessuno",
    "nessunooo": "nessuno",
    "notiziaa": "notizia",
    "notiziaaa": "notizia",
    "nuovoo": "nuovo",
    "nuovooo": "nuovo",
    "occasionee": "occasione",
    "occasioneee": "occasione",
    "occorreree": "occorrere",
    "occorrereee": "occorrere",
    "offriree": "offrire",
    "offrireee": "offrire",
    "oggettoo": "oggetto",
    "oggettooo": "oggetto",
    "oggiì": "oggi",
    "ognunoo": "ognuno",
    "ognunooo": "ognuno",
    "opinionee": "opinione",
    "opinioneee": "opinione",
    "organizzaree": "organizzare",
    "organizzareee": "organizzare",
    "osservaree": "osservare",
    "osservareee": "osservare",
    "ottimoo": "ottimo",
    "ottimooo": "ottimo",
    "paginaa": "pagina",
    "paginaaa": "pagina",
    "parlaree": "parlare",
    "parlareee": "parlare",
    "particolaree": "particolare",
    "particolareee": "particolare",
    "passaree": "passare",
    "passareee": "passare",
    "pensaree": "pensare",
    "pensareee": "pensare",
    "perche": "perché",
    "perche'": "perché",
    "perchè": "perché",
    "perchèmai": "perché mai",
    "perchèno": "perché no",
    "percio": "perciò",
    "percio'": "perciò",
    "perfezionee": "perfezione",
    "perfezioneee": "perfezione",
    "pericoloo": "pericolo",
    "pericolooo": "pericolo",
    "perlomeno": "per lo meno",
    "pero": "però",
    "pero'": "però",
    "personaa": "persona",
    "personaaa": "persona",
    "piacee": "piace",
    "piaceee": "piace",
    "pienoo": "pieno",
    "pienooo": "pieno",
    "piu": "più",
    "piu'": "più",
    "pocoo": "poco",
    "pocooo": "poco",
    "pocoò": "poco",
    "possibilee": "possibile",
    "possibileee": "possibile",
    "poteree": "potere",
    "potereee": "potere",
    "pò": "può",
    "pòi": "poi",
    "prblema": "problema",
    "prblemi": "problemi",
    "prenderee": "prendere",
    "prendereee": "prendere",
    "prepararee": "preparare",
    "preparareee": "preparare",
    "presentaree": "presentare",
    "presentareee": "presentare",
    "problemaa": "problema",
    "problemaaa": "problema",
    "progettaree": "progettare",
    "progettareee": "progettare",
    "proprioo": "proprio",
    "propriooo": "proprio",
    "provaree": "provare",
    "provareee": "provare",
    "pubblicoo": "pubblico",
    "pubblicooo": "pubblico",
    "puo": "può",
    "puo'": "può",
    "qual'è": "qual è",
    "qualcosaa": "qualcosa",
    "qualcosaaa": "qualcosa",
    "qualcunoo": "qualcuno",
    "qualcunooo": "qualcuno",
    "qualunqe": "qualunque",
    "qualunqu": "qualunque",
    "questae": "questa è",
    "questiè": "questi è",
    "questoe": "questo è",
    "questoè": "questo è",
    "ragazzoo": "ragazzo",
    "ragazzooo": "ragazzo",
    "ragionee": "ragione",
    "ragioneee": "ragione",
    "rapidamentee": "rapidamente",
    "rapidamenteee": "rapidamente",
    "realizzaree": "realizzare",
    "realizzareee": "realizzare",
    "riceveree": "ricevere",
    "ricevereee": "ricevere",
    "riccordare": "ricordare",
    "riccordato": "ricordato",
    "riccordi": "ricordi",
    "riccordo": "ricordo",
    "ricordaree": "ricordare",
    "ricordareee": "ricordare",
    "risolveree": "risolvere",
    "risolvereee": "risolvere",
    "rispostaa": "risposta",
    "rispostaaa": "risposta",
    "ritornaree": "ritornare",
    "ritornareee": "ritornare",
    "salutaree": "salutare",
    "salutareee": "salutare",
    "saperee": "sapere",
    "sapereee": "sapere",
    "scenderee": "scendere",
    "scendereee": "scendere",
    "scriveree": "scrivere",
    "scrivereee": "scrivere",
    "scrivree": "scrivere",
    "seguiree": "seguire",
    "seguireee": "seguire",
    "sentiree": "sentire",
    "sentireee": "sentire",
    "senzaltro": "senz’altro",
    "senzaltroo": "senz’altro",
    "seza": "senza",
    "senxa": "senza",
    "sicuramete": "sicuramente",
    "sicuramnete": "sicuramente",
    "significatoo": "significato",
    "significatooo": "significato",
    "silenzioo": "silenzio",
    "silenziooo": "silenzio",
    "situazionee": "situazione",
    "situazioneee": "situazione",
    "sìa": "sia",
    "solamentee": "solamente",
    "solamenteee": "solamente",
    "soluzine": "soluzione",
    "soluzone": "soluzione",
    "soprattuto": "soprattutto",
    "sopratutto": "soprattutto",
    "sòno": "sono",
    "speraree": "sperare",
    "sperareee": "sperare",
    "spiegaree": "spiegare",
    "spiegareee": "spiegare",
    "staree": "stare",
    "stareee": "stare",
    "stradaa": "strada",
    "stradaaa": "strada",
    "studiaree": "studiare",
    "studiareee": "studiare",
    "stà": "sta",
    "successoo": "successo",
    "successooo": "successo",
    "sufficientee": "sufficiente",
    "sufficienteee": "sufficiente",
    "superaree": "superare",
    "superareee": "superare",
    "svilupparee": "sviluppare",
    "sviluppareee": "sviluppare",
    "svolgeree": "svolgere",
    "svolgereee": "svolgere",
    "tagliaree": "tagliare",
    "tagliareee": "tagliare",
    "tastieraa": "tastiera",
    "tastieraaa": "tastiera",
    "tavoloo": "tavolo",
    "tavolooo": "tavolo",
    "tecnologiaa": "tecnologia",
    "tecnologiaaa": "tecnologia",
    "teh": "the",
    "telefonaree": "telefonare",
    "telefonareee": "telefonare",
    "telefonoo": "telefono",
    "telefonooo": "telefono",
    "tematichee": "tematiche",
    "tematicheee": "tematiche",
    "tempose": "tempo",
    "tempò": "tempo",
    "tendenzialmentee": "tendenzialmente",
    "tendenzialmenteee": "tendenzialmente",
    "terminaree": "terminare",
    "terminareee": "terminare",
    "terribilee": "terribile",
    "terribileee": "terribile",
    "terribilmentee": "terribilmente",
    "terribilmenteee": "terribilmente",
    "tesseraa": "tessera",
    "tesseraaa": "tessera",
    "toglieree": "togliere",
    "togliereee": "togliere",
    "tornaree": "tornare",
    "tornareee": "tornare",
    "tornatoo": "tornato",
    "tornatooo": "tornato",
    "trasferiree": "trasferire",
    "trasferireee": "trasferire",
    "trasmetteree": "trasmettere",
    "trasmettereee": "trasmettere",
    "trovaree": "trovare",
    "trovareee": "trovare",
    "trovatoo": "trovato",
    "trovatooo": "trovato",
    "tutta altra": "tuttaltra",
    "tutta parte": "tuttaparte",
    "tuttaltra": "tutta altra",
    "tuttaltro": "tuto altro",
    "tuttaparte": "tutta parte",
    "tuttaviaa": "tuttavia",
    "tuttaviaaa": "tuttavia",
    "tuttinsieme": "tutti insieme",
    "udiree": "udire",
    "udireee": "udire",
    "ufficialmentee": "ufficialmente",
    "ufficialmenteee": "ufficialmente",
    "ultimoo": "ultimo",
    "ultimooo": "ultimo",
    "un amica": "un’amica",
    "un altra": "un’altra",
    "un pò": "un po'",
    "unaltre": "un altro",
    "unaltro": "un altro",
    "unionee": "unione",
    "unioneee": "unione",
    "utilitàà": "utilità",
    "utilita'": "utilità",
    "utilizzaree": "utilizzare",
    "utilizzareee": "utilizzare",
    "valoree": "valore",
    "valoreee": "valore",
    "vederee": "vedere",
    "vedereee": "vedere",
    "vedutoo": "veduto",
    "vedutooo": "veduto",
    "velocementee": "velocemente",
    "velocementeee": "velocemente",
    "velocitàà": "velocità",
    "velocita'": "velocità",
    "venderee": "vendere",
    "vendereee": "vendere",
    "venerdi": "venerdì",
    "veramentee": "veramente",
    "veramenteee": "veramente",
    "verificaree": "verificare",
    "verificareee": "verificare",
    "veroo": "vero",
    "verooo": "vero",
    "veroò": "vero",
    "vestiree": "vestire",
    "vestireee": "vestire",
    "viaggiaree": "viaggiare",
    "viaggiareee": "viaggiare",
    "vicinanzee": "vicinanze",
    "vicinanzeee": "vicinanze",
    "vicinoo": "vicino",
    "vicinooo": "vicino",
    "vinceree": "vincere",
    "vincereee": "vincere",
    "vincitoree": "vincitore",
    "vincitoreee": "vincitore",
    "visionee": "visione",
    "visioneee": "visione",
    "vivacee": "vivace",
    "vivaceee": "vivace",
    "viveree": "vivere",
    "vivereee": "vivere",
    "vogio": "voglio",
    "vogglia": "voglia",
    "vogliaaa": "voglia",
    "vogglio": "voglio",
    "voleree": "volere",
    "volereee": "volere",
    "voltaaa": "volta",
    "voltooo": "volto",
    "voltoooo": "volto",
    "zainoo": "zaino",
    "zainooo": "zaino",
    "zuccheroo": "zucchero",
    "zuccherooo": "zucchero"
]

/// Restituisce una lista di stringhe descrittive degli errori trovati.
func trovaErrori(in testo: String) -> [String] {
    var problemi: [String] = []
    for (err, corr) in correzioni {
        if testo.contains(err) {
            problemi.append("'\(err)' → '\(corr)'")
        }
    }
    return problemi
}

/// Applica tutte le correzioni al testo.
func applicaCorrezioni(a testo: String) -> String {
    var testoModificato = testo
    for (err, corr) in correzioni {
        testoModificato = testoModificato.replacingOccurrences(of: err, with: corr)
    }
    return testoModificato
}